version: '2.1'

services:
  api-reglas:
    image: api-reglas
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
    depends_on:
      - db
      - api-realacionados
  api-realacionados:
    image: api-realacionados
    build: ../api-relacionados
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
  db:
    build: ./sql
    ports:
      - 3306:3306
